### ISSUE TITLE
Getting Exception

### ISSUE THREAD

**Issue by paulushub** [Microsoft/CodePlexWorkItemMigrator#3]
I am getting the following error/exception when trying to migrate my issues.
ERROR - An unexpected exception was encountered while running migration. Exception message: The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.

Codeplex project: https://sharpvectors.codeplex.com/
GitHub Repo: https://github.com/ElinamLLC/SharpVectors
It is created with the account @paulushub in an organization reposition ElinamLLC

Tried the following commands
Microsoft.CodePlex.Migration.WorkItemMigrator.exe -p SharpVectors -o paulushub -r SharpVectors -t XXX

Microsoft.CodePlex.Migration.WorkItemMigrator.exe -p sharpVectors -o paulushub -r SharpVectors -t XXX

Microsoft.CodePlex.Migration.WorkItemMigrator.exe -p SharpVectors -o paulushub -r ElinamLLC/SharpVectors -t XXX

**XXX** is the Github personal token created with first repo scope and then updated with all scopes checked.

**Comment by jascam** [comment]
Hello,

This error sounds like the GitHub access token does not have search permissions for your repo.  Can you confirm that when you created the access token you selected the check boxes for repo?

**Comment by paulushub** [comment]
Hello,
Thanks for the reply. I tried it twice. The first time, I checked only the repo boxes. The second time or current, I checked all boxes including the repo. Both cases gave the same error. 

I tried another repository, directly under @paulushub (i.e. not part of an organization) and got the same error.

**Comment by paulushub** [comment]
Hello,

Is there any way I could simply download all the Codeplex issues and manually add them to the Github?

**Comment by jascam** [comment]
That is very strange.  I will investigate the error you are seeing to see if I can reproduce it and hopefully come up with a solution.

Regarding exporting the work items, you can use the "-WhatIf" parameter to have the WorkItemMigrator write the work items to the console.  If you run the tool and redirected the output to a file that should give you the work items from CodePlex as a JSON file however since I don't have a good solution for adding these to GitHub once you generate the file I would like to try and get the import working for you.

**Comment by jascam** [comment]
I have managed to reproduce the issue you are seeing and I think I have a work around.  Can you try:
Microsoft.CodePlex.Migration.WorkItemMigrator.exe -p SharpVectors **-o ElinamLLC** -r SharpVectors -t XXX
(using the proper token for -t).

The -o is passed to GitHub as the repository owner and in this case since the repo is under a different organization that organization is considered the owner.

**Comment by paulushub** [comment]
Hello Jason,
Thanks so much for the time and the support. By the warning message, it is going to be slow, but I can confirm that it is now working and in progress (10 out of 54 imported and confirmed on Github). 
Again, thanks for helping to resolve this issue.
